//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanNuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedTable
    {
        public int id { get; set; }
        public Nullable<int> idTable { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerAddress { get; set; }
        public string BookDate { get; set; }
        public string BookTimeStart { get; set; }
        public string BookTimeEnd { get; set; }
    
        public virtual Table Table { get; set; }
        public virtual Table u { get; set; }
    }
}
