//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanNuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int id { get; set; }
        [Display(Name ="Tên đăng nhập")]
        public string Username { get; set; }
        [Display(Name = "Tên hiện thị")]
        public string DisplayName { get; set; }
        [Display(Name = "Mật khẩu")]
        public string Password { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
